apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      containers:
        - name: website
          image: avinashburri8/amazon-clone:latest # Replace with your Docker image from DockerHub or your private registry
          ports:
            - containerPort: 80
